// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces_test.go -package=editor -self_package=ef/editor
//

// Package editor is a generated GoMock package.
package editor

import (
	reflect "reflect"

	tcell "github.com/gdamore/tcell/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockScreenRenderer is a mock of ScreenRenderer interface.
type MockScreenRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockScreenRendererMockRecorder
	isgomock struct{}
}

// MockScreenRendererMockRecorder is the mock recorder for MockScreenRenderer.
type MockScreenRendererMockRecorder struct {
	mock *MockScreenRenderer
}

// NewMockScreenRenderer creates a new mock instance.
func NewMockScreenRenderer(ctrl *gomock.Controller) *MockScreenRenderer {
	mock := &MockScreenRenderer{ctrl: ctrl}
	mock.recorder = &MockScreenRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreenRenderer) EXPECT() *MockScreenRendererMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockScreenRenderer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockScreenRendererMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockScreenRenderer)(nil).Close))
}

// PollEvent mocks base method.
func (m *MockScreenRenderer) PollEvent() tcell.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollEvent")
	ret0, _ := ret[0].(tcell.Event)
	return ret0
}

// PollEvent indicates an expected call of PollEvent.
func (mr *MockScreenRendererMockRecorder) PollEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollEvent", reflect.TypeOf((*MockScreenRenderer)(nil).PollEvent))
}

// PostEvent mocks base method.
func (m *MockScreenRenderer) PostEvent(ev tcell.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostEvent", ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostEvent indicates an expected call of PostEvent.
func (mr *MockScreenRendererMockRecorder) PostEvent(ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostEvent", reflect.TypeOf((*MockScreenRenderer)(nil).PostEvent), ev)
}

// Render mocks base method.
func (m *MockScreenRenderer) Render(panes []*Pane, activePaneIdx int, mode Mode, inputState *InputState, splitMode SplitMode) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Render", panes, activePaneIdx, mode, inputState, splitMode)
}

// Render indicates an expected call of Render.
func (mr *MockScreenRendererMockRecorder) Render(panes, activePaneIdx, mode, inputState, splitMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockScreenRenderer)(nil).Render), panes, activePaneIdx, mode, inputState, splitMode)
}

// Resume mocks base method.
func (m *MockScreenRenderer) Resume() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume")
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockScreenRendererMockRecorder) Resume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockScreenRenderer)(nil).Resume))
}

// Size mocks base method.
func (m *MockScreenRenderer) Size() (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Size indicates an expected call of Size.
func (mr *MockScreenRendererMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockScreenRenderer)(nil).Size))
}

// Suspend mocks base method.
func (m *MockScreenRenderer) Suspend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend")
	ret0, _ := ret[0].(error)
	return ret0
}

// Suspend indicates an expected call of Suspend.
func (mr *MockScreenRendererMockRecorder) Suspend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockScreenRenderer)(nil).Suspend))
}

// Sync mocks base method.
func (m *MockScreenRenderer) Sync() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Sync")
}

// Sync indicates an expected call of Sync.
func (mr *MockScreenRendererMockRecorder) Sync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockScreenRenderer)(nil).Sync))
}

// MockEventPoster is a mock of EventPoster interface.
type MockEventPoster struct {
	ctrl     *gomock.Controller
	recorder *MockEventPosterMockRecorder
	isgomock struct{}
}

// MockEventPosterMockRecorder is the mock recorder for MockEventPoster.
type MockEventPosterMockRecorder struct {
	mock *MockEventPoster
}

// NewMockEventPoster creates a new mock instance.
func NewMockEventPoster(ctrl *gomock.Controller) *MockEventPoster {
	mock := &MockEventPoster{ctrl: ctrl}
	mock.recorder = &MockEventPosterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPoster) EXPECT() *MockEventPosterMockRecorder {
	return m.recorder
}

// PostEvent mocks base method.
func (m *MockEventPoster) PostEvent(ev tcell.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostEvent", ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostEvent indicates an expected call of PostEvent.
func (mr *MockEventPosterMockRecorder) PostEvent(ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostEvent", reflect.TypeOf((*MockEventPoster)(nil).PostEvent), ev)
}

// MockFileWatcherService is a mock of FileWatcherService interface.
type MockFileWatcherService struct {
	ctrl     *gomock.Controller
	recorder *MockFileWatcherServiceMockRecorder
	isgomock struct{}
}

// MockFileWatcherServiceMockRecorder is the mock recorder for MockFileWatcherService.
type MockFileWatcherServiceMockRecorder struct {
	mock *MockFileWatcherService
}

// NewMockFileWatcherService creates a new mock instance.
func NewMockFileWatcherService(ctrl *gomock.Controller) *MockFileWatcherService {
	mock := &MockFileWatcherService{ctrl: ctrl}
	mock.recorder = &MockFileWatcherServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileWatcherService) EXPECT() *MockFileWatcherServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFileWatcherService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFileWatcherServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFileWatcherService)(nil).Close))
}

// UpdateModTime mocks base method.
func (m *MockFileWatcherService) UpdateModTime(filename string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateModTime", filename)
}

// UpdateModTime indicates an expected call of UpdateModTime.
func (mr *MockFileWatcherServiceMockRecorder) UpdateModTime(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModTime", reflect.TypeOf((*MockFileWatcherService)(nil).UpdateModTime), filename)
}

// Watch mocks base method.
func (m *MockFileWatcherService) Watch(filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockFileWatcherServiceMockRecorder) Watch(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockFileWatcherService)(nil).Watch), filename)
}

// MockConfigProvider is a mock of ConfigProvider interface.
type MockConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockConfigProviderMockRecorder
	isgomock struct{}
}

// MockConfigProviderMockRecorder is the mock recorder for MockConfigProvider.
type MockConfigProviderMockRecorder struct {
	mock *MockConfigProvider
}

// NewMockConfigProvider creates a new mock instance.
func NewMockConfigProvider(ctrl *gomock.Controller) *MockConfigProvider {
	mock := &MockConfigProvider{ctrl: ctrl}
	mock.recorder = &MockConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigProvider) EXPECT() *MockConfigProviderMockRecorder {
	return m.recorder
}

// GetFileTypeConfig mocks base method.
func (m *MockConfigProvider) GetFileTypeConfig(ftName string) FileTypeConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileTypeConfig", ftName)
	ret0, _ := ret[0].(FileTypeConfig)
	return ret0
}

// GetFileTypeConfig indicates an expected call of GetFileTypeConfig.
func (mr *MockConfigProviderMockRecorder) GetFileTypeConfig(ftName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileTypeConfig", reflect.TypeOf((*MockConfigProvider)(nil).GetFileTypeConfig), ftName)
}

// GetKeyMappings mocks base method.
func (m *MockConfigProvider) GetKeyMappings() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyMappings")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetKeyMappings indicates an expected call of GetKeyMappings.
func (mr *MockConfigProviderMockRecorder) GetKeyMappings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyMappings", reflect.TypeOf((*MockConfigProvider)(nil).GetKeyMappings))
}

// GetMaps mocks base method.
func (m *MockConfigProvider) GetMaps() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaps")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetMaps indicates an expected call of GetMaps.
func (mr *MockConfigProviderMockRecorder) GetMaps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaps", reflect.TypeOf((*MockConfigProvider)(nil).GetMaps))
}

// MockFileTypeDetector is a mock of FileTypeDetector interface.
type MockFileTypeDetector struct {
	ctrl     *gomock.Controller
	recorder *MockFileTypeDetectorMockRecorder
	isgomock struct{}
}

// MockFileTypeDetectorMockRecorder is the mock recorder for MockFileTypeDetector.
type MockFileTypeDetectorMockRecorder struct {
	mock *MockFileTypeDetector
}

// NewMockFileTypeDetector creates a new mock instance.
func NewMockFileTypeDetector(ctrl *gomock.Controller) *MockFileTypeDetector {
	mock := &MockFileTypeDetector{ctrl: ctrl}
	mock.recorder = &MockFileTypeDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileTypeDetector) EXPECT() *MockFileTypeDetectorMockRecorder {
	return m.recorder
}

// DetectFileType mocks base method.
func (m *MockFileTypeDetector) DetectFileType(filename string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectFileType", filename)
	ret0, _ := ret[0].(string)
	return ret0
}

// DetectFileType indicates an expected call of DetectFileType.
func (mr *MockFileTypeDetectorMockRecorder) DetectFileType(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectFileType", reflect.TypeOf((*MockFileTypeDetector)(nil).DetectFileType), filename)
}

// GetConfig mocks base method.
func (m *MockFileTypeDetector) GetConfig(ft string) FileTypeConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ft)
	ret0, _ := ret[0].(FileTypeConfig)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockFileTypeDetectorMockRecorder) GetConfig(ft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockFileTypeDetector)(nil).GetConfig), ft)
}

// GetFormatter mocks base method.
func (m *MockFileTypeDetector) GetFormatter(ft string) Formatter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormatter", ft)
	ret0, _ := ret[0].(Formatter)
	return ret0
}

// GetFormatter indicates an expected call of GetFormatter.
func (mr *MockFileTypeDetectorMockRecorder) GetFormatter(ft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormatter", reflect.TypeOf((*MockFileTypeDetector)(nil).GetFormatter), ft)
}

// GetHighlighter mocks base method.
func (m *MockFileTypeDetector) GetHighlighter(ft string) SyntaxHighlighter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighlighter", ft)
	ret0, _ := ret[0].(SyntaxHighlighter)
	return ret0
}

// GetHighlighter indicates an expected call of GetHighlighter.
func (mr *MockFileTypeDetectorMockRecorder) GetHighlighter(ft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighlighter", reflect.TypeOf((*MockFileTypeDetector)(nil).GetHighlighter), ft)
}
